routes:

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: 'tag:-[hash-de,hash-fr]'
  /fr/:
    permalink: /fr/{slug}/
    template: index-fr
    filter: 'tag:hash-fr'

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
